version: 2.1

orbs:
  package:
    executors:
      node-11:
        docker:
          - image: "circleci/node:12-stretch"
    jobs:
      build-node:
        executor: node-12
        steps:
          - run: yarn versions
          - checkout
          - restore_cache:
              keys:
                - node-v1-{{ checksum "yarn.lock" }}
                - node-v1-
          - run: yarn install --frozen-lockfile
          - run: yarn run test
          - save_cache:
              key: node-v1-{{ checksum "yarn.lock" }}
              paths:
                - node_modules

workflows:
  build:
    jobs:
      - package/build-node
